### ISSUE TITLE
Unable to craft Glass Pane's

### ISSUE THREAD

**Issue by mouse0270** [IchHabeHunger54/SlabsStairsWalls#1]
Basically your mod uses the same recipe to craft Glass Wall's, so every time you go to craft one you instead get Glass Walls.

I would suggest changing this recipe to use glass panes instead of glass. It would add a step no other wall needs to be crafted, but it will work with vanilla minecraft much better.

**Comment by IchHabeHunger54** [comment]
Thank you, uploaded a new version with this fixed! :D
